'use strict';
// Fixture-only screen. Claude integration contract: ../DESIGN_HANDOFF.md
const spots=[
{id:'s1',name:'골목 안 작은 이자카야',category:'이자카야',area:'후쿠오카 · 다이묘',memo:'첫날 저녁, 카운터 자리에서',image:'assets/izakaya.webp'},
{id:'s2',name:'햇살 드는 커피 바',category:'카페',area:'후쿠오카 · 야쿠인',memo:'느긋하게 시작하는 아침',image:'assets/cafe.webp'},
{id:'s3',name:'취향을 찾는 사케 숍',category:'주판점',area:'후쿠오카 · 하카타',memo:'집에 가져갈 한 병 고르기',image:'assets/sake.webp'},
{id:'s4',name:'퇴근길 한 잔',category:'이자카야',area:'후쿠오카 · 텐진',memo:'산책 끝에 가볍게 들르기',image:'assets/izakaya.webp'},
{id:'s5',name:'오후의 작은 카페',category:'카페',area:'후쿠오카 · 오호리',memo:'많이 걸은 날, 잠깐 쉬기',image:'assets/cafe.webp'},
{id:'s6',name:'동네의 주판점',category:'주판점',area:'후쿠오카 · 야쿠인',memo:'선물할 술도 잊지 말기',image:'assets/sake.webp'}];
const cities=[{name:'후쿠오카',label:'FUKUOKA, JAPAN',country:'일본'},{name:'삿포로',label:'SAPPORO, JAPAN',country:'일본'},{name:'뉴욕',label:'NEW YORK, USA',country:'미국'}];
spots.forEach(p=>p.city='후쿠오카');
spots.push(
{id:'s7',city:'삿포로',name:'눈 오는 날의 커피',category:'카페',area:'삿포로 · 오도리',memo:'산책하다 따뜻한 한 잔',image:'assets/cafe.webp'},
{id:'s8',city:'삿포로',name:'저녁의 작은 술집',category:'이자카야',area:'삿포로 · 스스키노',memo:'하루를 마무리하는 자리',image:'assets/izakaya.webp'},
{id:'s9',city:'삿포로',name:'한 병의 홋카이도',category:'주판점',area:'삿포로 · 삿포로역',memo:'여행의 기억을 가져가기',image:'assets/sake.webp'},
{id:'s10',city:'뉴욕',name:'동네 커피 브레이크',category:'카페',area:'뉴욕 · 브루클린',memo:'걷다 발견한 쉬어갈 곳',image:'assets/cafe.webp'},
{id:'s11',city:'뉴욕',name:'작은 일본식 식당',category:'음식점',area:'뉴욕 · 이스트빌리지',memo:'저녁 약속을 잡아둔 곳',image:'assets/izakaya.webp'},
{id:'s12',city:'뉴욕',name:'취향을 고르는 가게',category:'쇼핑',area:'뉴욕 · 맨해튼',memo:'친구에게 줄 선물 한 병',image:'assets/sake.webp'});
let city='후쿠오카';
let filter='전체' ,selected=new Set(),route=new Set(),selecting=false;
const $=s=>document.querySelector(s),sheet=$('#sheet');
function render(){const q=$('#search').value.trim().toLowerCase();const list=spots.filter(p=>p.city===city&&(filter==='전체'||p.category===filter)&&[p.name,p.area,p.category,p.memo].some(v=>v.toLowerCase().includes(q)));$('#count').textContent=list.length;$('#clear').hidden=!q;$('#empty').hidden=!!list.length;$('#grid').innerHTML=list.map(p=>`<article class="spot ${selected.has(p.id)?'selected':''}"><button class="spot-open" data-detail="${p.id}" aria-label="${p.name} 상세 보기"><img class="photo" src="${p.image}" alt="${p.category} 분위기 참고용 사진" loading="lazy" decoding="async" width="320" height="320"><div class="spot-info"><span class="category">${p.category}</span><h3>${p.name}</h3><p class="area">${p.area}</p><p class="memo">${p.memo}</p></div></button><button class="pick" data-pick="${p.id}" aria-label="${p.name} 선택" aria-pressed="${selected.has(p.id)}">${selected.has(p.id)?'✓':'＋'}</button></article>`).join('');const activeSelected=spots.filter(p=>p.city===city&&selected.has(p.id)).length;$('#selectionbar').hidden=!activeSelected;$('#selectedCount').textContent=activeSelected;$('#selectMode').textContent=selecting?'선택 마치기':'장소 선택';}
function toggle(id){selected.has(id)?selected.delete(id):selected.add(id);render()}
function open(title,html){$('#sheetLabel').textContent=title;$('#sheetContent').innerHTML=html;if(!sheet.open)sheet.showModal()}
function detail(id){const p=spots.find(p=>p.id===id);open('샘플 장소',`<div class="detail"><img class="detail-photo" width="640" height="427" decoding="async" src="${p.image}" alt="${p.category} 분위기 참고 사진"><h2>${p.name}</h2><span class="category">${p.category}</span><p>${p.area}</p><p>“${p.memo}”</p><button class="primary" data-detail-pick="${id}">${selected.has(id)?'선택에서 빼기':'오늘 갈 곳으로 선택'}</button><a target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(p.area+' '+p.category)}">Google Maps에서 주변 ${p.category} 찾기 ↗</a><small>실제 매장이 아닌 디자인 예시입니다. 사진은 분위기 참고용이며 주소·전화번호는 실제 장소 연결 후 표시됩니다.</small></div>`)}
function showRoute(){const list=spots.filter(p=>p.city===city&&route.has(p.id));open(city+' · 오늘 동선',`<div class="detail"><h2>오늘은 이곳으로.</h2><p>${list.length?'담아 둔 '+list.length+'곳을 확인하세요.':'마음에 드는 장소를 먼저 골라보세요.'}</p>${list.map((p,i)=>`<div class="route-row"><span>${i+1}</span><img src="${p.image}" width="56" height="56" decoding="async" alt=""><div><b>${p.name}</b><p>${p.area}</p></div><button data-remove="${p.id}" aria-label="${p.name} 동선에서 빼기">×</button></div>`).join('')}<small>디자인 체험용 목록입니다. 최단거리 계산과 교통 안내는 아직 연결되지 않았습니다.</small><button class="primary" data-dismiss>스팟 더 고르기</button></div>`)}
function profile(){open('내 프로필',`<div class="profile"><div class="avatar">Y</div><h2>나의 여행 기록</h2><p>가고 싶은 곳을 하나씩 모으는 중</p><div class="stats"><div><b>${spots.length}</b><span>저장한 스팟</span></div><div><b>${cities.length}</b><span>도시</span></div><div><b>${route.size}</b><span>오늘 갈 곳</span></div></div><p>${city} · 샘플 컬렉션</p><button class="primary" data-dismiss>내 스팟으로 돌아가기</button><p>샘플 프로필입니다.</p></div>`)}
function updateCity(){
 $('#cityName').textContent=city;$('#albumCity').textContent=cities.find(c=>c.name===city).label;
 $('.filters').innerHTML=['전체',...new Set(spots.filter(p=>p.city===city).map(p=>p.category))].map(c=>`<button data-filter="${c}" class="${c===filter?'active':''}" aria-pressed="${c===filter}">${c}</button>`).join('');render();
}
function chooseCity(name){city=name;filter='전체';selecting=false;$('#search').value='';updateCity();sheet.close()}
function cityPicker(){open('여행지 선택',`<div class="detail"><h2>어디로 떠나세요?</h2><p>저장한 장소가 있는 도시를 골라주세요.</p><div class="city-options">${cities.map(c=>`<button class="city-option ${city===c.name?'chosen':''}" data-city="${c.name}"><span class="city-initial">${c.name.slice(0,1)}</span><span><b>${c.name}</b><small>${c.country} · 저장한 스팟 ${spots.filter(p=>p.city===c.name).length}곳</small></span><span class="city-check">${city===c.name?'✓':'›'}</span></button>`).join('')}</div><p class="inline-note">지금 있는 곳과 다른 도시도 준비할 수 있어요.</p><small>현재는 3개 도시의 샘플입니다. 실제 서비스에서는 가져온 장소에 따라 도시가 추가됩니다.</small><button class="primary" data-import>다른 도시의 장소 가져오기</button></div>`)}
function add(){open('내 장소 가져오기',`<div class="detail import-flow"><span class="flow-tag">가져오기 화면 체험</span><h2>저장한 곳,<br>그대로 모아볼까요?</h2><p>구글맵에서 내보낸 파일로 시작해요.</p><div class="file-surface"><span class="file-symbol">↓</span><b>내보낸 파일 가져오기</b><span>ZIP · CSV</span><span class="not-ready">실제 파일 연결 준비 중</span></div><button class="primary" data-import-demo>샘플 파일로 체험하기</button><small>실제 파일을 읽지 않는 디자인 체험입니다.</small><details class="import-help"><summary>구글맵에서 파일은 어떻게 받나요?</summary><ol><li>Google Takeout을 열어요.</li><li>‘저장됨(Saved)’ 항목을 선택해 내보내세요.</li><li>파일을 받은 뒤 이 화면에서 가져옵니다.</li></ol><a href="https://takeout.google.com/" target="_blank" rel="noopener noreferrer">Google Takeout 열기 ↗</a><p>계정에 따라 내보내기 준비 시간이 걸릴 수 있어요.</p></details><a class="legacy-import" href="classic.html">내 CSV는 기존 앱에서 가져오기 ↗</a></div>`)}
function importDemo(){open('가져오기 결과 · 샘플',`<div class="detail import-flow"><span class="flow-tag">예시 결과</span><h2>12곳을 정리했어요.</h2><p>도시별로 모아뒀어요. 어디부터 볼까요?</p><div class="import-summary"><span><b>12</b>정리된 장소</span><span><b>3</b>도시</span><span><b>1</b>위치 확인 필요</span></div>${cities.map(c=>`<button class="city-option" data-city="${c.name}"><span class="city-initial">${c.name.slice(0,1)}</span><span><b>${c.name}</b><small>${spots.filter(p=>p.city===c.name).length}곳</small></span><span class="city-check">↗</span></button>`).join('')}<details class="import-help"><summary>위치가 불분명한 1곳 확인하기</summary><p>‘역 앞 카페’는 정확한 위치를 찾지 못했어요. 주소나 지도 링크로 나중에 확인할 수 있어요.</p><small>일부 장소를 찾지 못해도 나머지 장소는 먼저 사용할 수 있도록 설계합니다.</small></details><small>가져오기 결과와 미확인 장소는 모두 예시이며, 실제 파일 분석 결과가 아닙니다.</small></div>`)}
function nearby(){open('내 주변',`<div class="detail"><h2>지금 가까운 곳부터.</h2><p>현재 위치를 출발점으로, ${city}에 저장한 장소를 가까운 순서로 보여줄 공간입니다.</p><div class="inline-note">선택한 여행지: ${city}<br>위치 권한은 이 기능을 사용할 때만 요청합니다.</div><small>GPS 연결 전인 디자인 미리보기입니다. 현재 위치를 수집하거나 거리순으로 정렬하지 않습니다.</small><button class="primary" data-dismiss>저장한 스팟 계속 보기</button><button class="text-button" data-city-picker>여행지 바꾸기</button></div>`)}
$('#search').addEventListener('input',render);$('#clear').onclick=()=>{$('#search').value='';render();$('#search').focus()};
$('.filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;document.querySelectorAll('[data-filter]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',x===b)});render()};
$('#reset').onclick=()=>{$('#search').value='';document.querySelector('[data-filter="전체"]').click()};
$('#grid').onclick=e=>{const pick=e.target.closest('[data-pick]');if(pick)return toggle(pick.dataset.pick);const b=e.target.closest('[data-detail]');if(b)selecting?toggle(b.dataset.detail):detail(b.dataset.detail)};
$('#selectMode').onclick=()=>{selecting=!selecting;render()};$('#close').onclick=()=>sheet.close();sheet.onclick=e=>{if(e.target===sheet)sheet.close()};
$('#sheetContent').onclick=e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.city)return chooseCity(b.dataset.city);if(b.hasAttribute('data-import'))return add();if(b.hasAttribute('data-import-demo'))return importDemo();if(b.hasAttribute('data-city-picker'))return cityPicker();if(b.hasAttribute('data-dismiss'))sheet.close();if(b.dataset.detailPick){toggle(b.dataset.detailPick);detail(b.dataset.detailPick)}if(b.dataset.remove){route.delete(b.dataset.remove);showRoute()}};
$('#addRoute').onclick=()=>{spots.filter(p=>p.city===city&&selected.has(p.id)).forEach(p=>{route.add(p.id);selected.delete(p.id)});selecting=false;render();showRoute()};
$('#route').onclick=showRoute;document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=profile);document.querySelectorAll('[data-add]').forEach(b=>b.onclick=add);
$('#browse').onclick=()=>$('.section-heading').scrollIntoView({behavior:'smooth',block:'start'});$('#home').onclick=()=>window.scrollTo({top:0,behavior:'smooth'});$('#collection').onclick=()=>$('.album').scrollIntoView({behavior:'smooth',block:'center'});
$('#cityPicker').onclick=cityPicker;$('#nearby').onclick=nearby;
updateCity();
